# Generated by Django 4.2.3 on 2023-07-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0002_usersubscriptions_userlikedsongs_userbannedsongs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlikedsongs",
            name="song_id",
        ),
        migrations.RemoveField(
            model_name="userlikedsongs",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="usersubscriptions",
            name="artist_id",
        ),
        migrations.RemoveField(
            model_name="usersubscriptions",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="UserBannedSongs",
        ),
        migrations.DeleteModel(
            name="UserLikedSongs",
        ),
        migrations.DeleteModel(
            name="UserSubscriptions",
        ),
    ]
