# Generated by Django 3.2 on 2023-07-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_remove_userlikedsongs_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
