# Generated by Django 3.2 on 2023-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
