# Generated by Django 4.2.3 on 2023-07-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("cover_url", models.CharField(blank=True, max_length=512, null=True)),
                ("song_uri", models.CharField(max_length=512)),
                ("lyrics", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("RU", "Russian"),
                            ("EN", "English"),
                            ("ES", "Spanish"),
                        ],
                        max_length=2,
                    ),
                ),
                ("instrumental", models.BooleanField()),
                ("explicit", models.BooleanField()),
                (
                    "genre",
                    models.CharField(
                        choices=[("Rock", "Rock"), ("Rap", "Rap"), ("Pop", "Pop")],
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artists", models.ManyToManyField(to="artist.artist")),
            ],
        ),
    ]
